spring:
  profiles:
    active: local
    group:
      local: db-local
      server: db-server
    include:
      - db
      - security
  datasource:
    driver-class-name: ${DATABASE_DRIVER}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
    open-in-view: false
    dialect: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect