import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({  
    //Login UI 
    container:{    
        flex: 1, 
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: "#D3D3DD", 
    },
    title:{
        width: 334,
        height: 59,
        backgroundColor: '#c7cfff',
        borderColor: '#fff',
        borderLeftWidth: 3,
        borderTopWidth: 3,
    },
    peepicon: {
        height: 90,
        width: 90,
        position: 'absolute',
        justifyContent: 'center',
        alignItems: 'center',
        top: '50%',
        left: '50%',
        transform: [{ translateX: -45 }, { translateY: '-60%' }],
    },
    textbox:{
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        position: 'relative',
        transform: [{ translateY: '20%' }],
    },
    text1: { //노랑
        color: '#ffdbb7',
        fontFamily: 'PF stardust ExtraBold',
        fontSize: 36,
        position: 'absolute',
        transform: [{ translateX: 4 }, { translateY: 2 }],
    },
    text2: { //보라
        color: '#9482ce',
        fontFamily: 'PF stardust ExtraBold',
        fontSize: 36,
        position: 'absolute',
        transform: [{ translateX: 2 }, { translateY: 1 }],
    },
    text3: { //하양
        color: '#fff',
        fontFamily: 'PF stardust ExtraBold',
        fontSize: 36,
    },
    topMargin:{
        width: 334,
        height: 38,
        backgroundColor: '#f3f8fe',
        borderColor: '#8787a3',
        borderTopWidth: 2,
        borderLeftWidth: 4,
        borderRightWidth: 4,
    },
    contents:{
        width: 334,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#f3f8fe',
        borderColor: '#8787a3',
        borderLeftWidth: 4,
        borderRightWidth: 4,
    },
    bottomMargin:{
        width: 334,
        height: 16,
        backgroundColor: '#f3f8fe',
        borderColor: '#8787a3',
        borderBottomWidth: 2,
        borderLeftWidth: 4,
        borderRightWidth: 4,
    },
    bottomOuterMargin:{
        width: 334,
        height: 12,
    },

    //Login 내부 Style
    pageTitle:{
        fontFamily: 'PF stardust ExtraBold',
        color: '#8787a3',
        fontSize: 14,
        textAlign: 'left',
        width: 284,
        marginBottom: 12,
    },
    inputBox: {
        fontFamily: 'PF stardust ExtraBold',
        color: '#8787a3',
        fontSize: 14,
        textAlign: 'left',
        width: 284,
        height: 45,
        backgroundColor: '#fff',
        borderColor: '#8787a3',
        borderWidth: 1,
        marginBottom: 8,
        padding: 10,
    },
    agreeButton: {
        width: 172,
        height: 36,
        backgroundColor: '#BfE1E0',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },    
    disagreeButton: {
        width: 172,
        height: 36,
        backgroundColor: '#BfE1E0',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },    
    nextButton: {
        width: 172,
        height: 36,
        backgroundColor: '#ffdbb7',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },
    buttonText: {
        fontFamily: 'PF stardust ExtraBold',
        color: '#8787A3',
        fontSize: 14,
        textAlign: 'center',
    },
    msgBox:{
        width: 284,
        flexDirection: 'row',
        marginBottom: 4,
        justifyContent: 'center',
        position: 'relative',
    },
    pageText:{
        fontFamily: 'PF stardust ExtraBold',
        color: '#8787a3',
        fontSize: 14,
        textAlign: 'left',
        marginBottom: 4,
    },
    errorMsg:{
        fontFamily: 'PF stardust ExtraBold',
        color: '#ff9b9b',
        fontSize: 14,
        textAlign: 'left',
        marginBottom: 4,
    },
    bottomContents:{
        width: 334,
        height: 38,
        alignItems: 'center',
    },
    bottomContentsText: {
        fontFamily: 'PF stardust ExtraBold',
        color: '#8787a3',
        fontSize: 14,
        textAlign: 'center',
        position: 'relative',
    },
    checkBox: {
        marginRight: 10,
    },

    //Modal
    modalContainer: {
        flex: 1, 
        justifyContent: 'center', 
        alignItems: 'center', 
        backgroundColor: 'rgba(0, 0, 0, 0.5)' 
    },
    modalContent: {
        width: 308, 
        height: 120 , 
        backgroundColor: '#f3f8fe',
        justifyContent: 'center', 
        alignItems: 'center',
        borderColor: '#8787a3',
        borderWidth: 4,
    },


});