import { StyleSheet } from 'react-native';

export const petstyles = StyleSheet.create({  
    PEEPInfoBox: {
        width: '100%',
        flexDirection: 'row', 
        minHeight: 120, 
        maxHeight: 200, 
        height: '24%', 
        justifyContent: 'flex-end' 
    },
    peepName_01: {
        color: "#8787A3",
        fontSize: 24,
        position: 'absolute',
        top: 1,                // 화면 상단에 배치
        left: 1,
    },
    peepName_02: {
        color: "#8787A3",
        fontSize: 24,
        position: 'absolute',
        top: -1,                // 화면 상단에 배치
        left: -1,
    },
    peepName_03: {
        color: "#8787A3",
        fontSize: 24,
        position: 'absolute',
        top: -1,                // 화면 상단에 배치
        left: 1,
    },
    peepName_04: {
        color: "#8787A3",
        fontSize: 24,
        position: 'absolute',
        top: 1,                // 화면 상단에 배치
        left: -1,
    },
    peepName_05: {
        color: "#8787A3",
        fontSize: 24,
        position: 'absolute',
        top: 2,                // 화면 상단에 배치
        left: 2,
    },
    peepName_06: {
        color: "#8787A3",
        fontSize: 24,
        position: 'absolute',
        top: 2,                // 화면 상단에 배치
        left: 0,
    },
    peepName_07: {
        color: "#8787A3",
        fontSize: 24,
        position: 'absolute',
        top: 0,                // 화면 상단에 배치
        left: 2,
    },    
    peepName_08: {
        color: "#fff",
        fontSize: 24,
    },
    PEEPInfoMessage: {
        width:  200,
        height: 56,
        backgroundColor: '#fff',
        borderWidth: 3,
        borderColor: '#B1ADCA',
        position: 'absolute',
        justifyContent: 'center',
        zIndex: 1,
        top: -20,
        left: -8,
    },
    PEEPRoom: {
        width: '100%',
        backgroundColor: '#D9D9D9',
        position: 'relative',
        justifyContent: 'flex-end', // 이미지가 바닥에 위치하도록 함
        alignItems: 'center', // 이미지가 수평으로 가운데 정렬되도록 설정 (선택사항)
        borderWidth: 4,
        borderColor: '#C7CFFF',
        borderRadius: 10,
    },
    PEEPRoomImg: {
        width: '100%',
        height: '100%',
        backgroundColor: '#D9D9D9',
        borderRadius: 10,
    },
    PEEPImg:{
        width: 140,
        height: 140,
        marginBottom: 24,
    },
    optionListText: {
        color: '#8787A3',
        textAlign: 'left',
    },


    //List
    pageTitle:{
        width: '100%',
        marginBottom: 16,
        flexDirection: 'row',
        alignItems: 'center',
    },
    pageTitleText: {
        color: '#8787A3',
        textAlign: 'left',
        fontSize: 20,
    },
    petListBox: {
        width: '100%',
        marginBottom: 12,
    },
    petList:{
        height: 102,
        backgroundColor: '#000',
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        padding: 8,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    petListShadow: {
        width: '100%',
        height: 102,
        backgroundColor: '#8787A3',
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        padding: 8,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        position: 'absolute',
        top: 2,
        left: 3,
    },
    favorites: {
        width: '10%',
        alignItems: 'flex-start',
        height: '100%',
    },
    favorites_non: {
    },
    favorites_check: {
    },
    favorites_shadow: {
        position: 'absolute',
        top: -2,
        left: -1,
    },
    petImg: {
        width: '30%',
        height: 50,
        alignItems: 'center',
        justifyContent: 'center',
    },
    petData: {
        width: '60%',
    },
    petInfo: {
        color: '#8787A3',
        fontSize: 20,
    },
    petNameShadow00: {
        color: '#8787A3',
        fontSize: 20,
        position: 'absolute',
        top: 2,
        left: 2,
    },
    petNameShadow01: {
        color: '#8787A3',
        fontSize: 20,
        position: 'absolute',
        top: 2,
        left: 1,
    },
    petNameShadow02: {
        color: '#8787A3',
        fontSize: 20,
        position: 'absolute',
        top: -1,
        left: 1,
    },
    petNameShadow03: {
        color: '#8787A3',
        fontSize: 20,
        position: 'absolute',
        top: -1,
        left: -1,
    },
    petNameShadow04: {
        color: '#8787A3',
        fontSize: 20,
        position: 'absolute',
        top: 1,
        left: 1,
    },
    petNameShadow05: {
        color: '#8787A3',
        fontSize: 20,
        position: 'absolute',
        top: 1,
        left: -1,
    },
    petName: {
        fontSize: 20,
    },
    petStats: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    petStatsText: {
        color: '#8787A3',
        fontSize: 12,
    },


    //addPeep
    addPeepBox: { 
        flex: 1, 
        width: '100%', 
        alignItems: 'center', 
        justifyContent: 'center',
        marginVertical: 20,
    },
    addPeepList:{
        marginVertical: 4,
    },
    addPeepText: {
        fontWeight: 'bold',
        color: '#8787A3',
        fontSize: 24,
    },
    addPeepTextShadow: {
        fontWeight: 'bold',
        color: '#8787A3',
        fontSize: 24,
        position: 'absolute',
        top: -1,
        left: 1,
    },

    //addPeepInfo
    addPeepInfoContainer: { 
        flex: 1,
        width: '100%', 
        alignItems: 'center', 
        justifyContent: 'center',
        marginVertical: 20,
    },
    addPeepInfoBoxShadow:{
        width: 310,
        height: 380,
        backgroundColor: '#8787A3',
        borderColor: '#8787A3',
        borderWidth: 2,
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        position: 'absolute',
        top: 2,
        left: 3,
    },
    addPeepInfoBox: {
        width: 310,
        height: 380,
        alignItems: 'center', 
        justifyContent: 'center',
        paddingHorizontal: 12,
        paddingVertical: 24,
        backgroundColor: '#fff',
        borderColor: '#8787A3',
        borderWidth: 2,
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
    },
    entryNumber: {
        width: 92,
        height: 24,
        justifyContent: 'center',
        alignSelf: 'flex-start',
        marginTop: 12,
        backgroundColor: '#fff',
    },
    entryNumberText:{
        color: '#8787A3',
        textAlign: 'center',
        fontSize: 20,
    },
    addPeepNameText:{
        color: '#fff',
        fontSize: 20,
        textAlign: 'left',
        marginBottom: 4,
    },
    addPeepNameTextShadow01: {
        color: '#8787A3',
        fontSize: 20,
        textAlign: 'left',
        position: 'absolute',
        top: 1,
        left: 1,
    },
    addPeepNameTextShadow02: {
        color: '#8787A3',
        fontSize: 20,
        textAlign: 'left',
        position: 'absolute',
        top: 1,
        left: -1,
    },
    addPeepNameTextShadow03: {
        color: '#8787A3',
        fontSize: 20,
        textAlign: 'left',
        position: 'absolute',
        top: -1,
        left: 1,
    },
    addPeepNameTextShadow04: {
        color: '#8787A3',
        fontSize: 20,
        textAlign: 'left',
        position: 'absolute',
        top: -1,
        left: -1,
    },
    addPeepNameTextShadow05: {
        color: '#8787A3',
        fontSize: 20,
        textAlign: 'left',
        position: 'absolute',
        top: 2,
        left: 2,
    },
    addPeepNameTextShadow06: {
        color: '#8787A3',
        fontSize: 20,
        textAlign: 'left',
        position: 'absolute',
        top: 2,
        left: 1,
    },
    addPeepNameTextShadow07: {
        color: '#8787A3',
        fontSize: 20,
        textAlign: 'left',
        position: 'absolute',
        top: 0,
        left: 2,
    },
    addPeepInfoText: {
        color: '#8787A3',
        fontSize: 16,
        textAlign: 'left',
    },
    addPeepMessage:{
        alignItems: 'center', 
        justifyContent: 'center',
        marginTop: 10,
    },
    addPeepInfoListBox: {
        width: '100%', 
        flexDirection: 'row', 
        justifyContent: 'center',
    },
    addPeepInfoList: {
        justifyContent: 'center',
        alignSelf: 'flex-start',
        flexDirection: 'column',
        marginRight: 12,
        marginBottom: 4,
    },
    petInfoMessage: {
        width: 270,
        alignItems: 'center', 
        justifyContent: 'center',
        marginTop: 16,
        marginBottom: 16,
    },

    //collection
    collectionlist: {
        flex: 1,
        justifyContent: 'center',
        flexDirection: 'row',
        flexWrap: 'wrap', 
    },
    collectioncard: {
        justifyContent: 'center',
        marginRight: 4,
        marginLeft: 4,
    },
    collections: {
        width: '100%',
        marginBottom: 4,
    },
    bookmark: {
        width: 44,
        height: 8,
        backgroundColor: '#8787A3',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
    },
    collection: {
        alignItems: 'center', 
        justifyContent: 'center',
        width: 132,
        height: 160,
        borderWidth: 1,
        borderColor: '#8787A3',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        borderBottomRightRadius: 10,
        position: 'absolute',
        top: 4,
        left: 8,
        padding: 12,
    },
    collectionShadow: {
        width: 136,
        height: 164,
        borderWidth: 1,
        backgroundColor: '#8787A3',
        borderColor: '#8787A3',
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
    },
    collectionPetImg: {
        alignItems: 'center', 
        justifyContent: 'center',
        width: '100%',
        height: '70%',
        marginBottom: 12,
    },
    collectionInfoBox:{
        width: '100%',
        textAlign: 'left',
        marginBottom: 2,
    },
    collectionInfoText: {
        color: '#8787A3',
        fontSize: 10,
    },
    collectionNameBox:{
        width: '100%',
        textAlign: 'left',
    },
    collectionNameText: {
        color: '#fff',
    },
    collectionNameTextShadow01: {
        color: '#8787A3',
        position: 'absolute',
        top: 1,
        left: 1,
    },
    collectionNameTextShadow02: {
        color: '#8787A3',
        position: 'absolute',
        top: 1,
        left: -1,
    },
    collectionNameTextShadow03: {
        color: '#8787A3',
        position: 'absolute',
        top: -1,
        left: 1,
    },
    collectionNameTextShadow04: {
        color: '#8787A3',
        position: 'absolute',
        top: -1,
        left: -1,
    },
    collectionNameTextShadow05: {
        color: '#8787A3',
        position: 'absolute',
        top: 2,
        left: 2,
    },
    collectionNameTextShadow06: {
        color: '#8787A3',
        position: 'absolute',
        top: 2,
        left: 0,
    },
    collectionNameTextShadow07: {
        color: '#8787A3',
        position: 'absolute',
        top: 0,
        left: 2,
    },
    collectionNameTextShadow08: {
        color: '#8787A3',
        position: 'absolute',
        top: 2,
        left: 1,
    },
    collectionNameTextShadow09: {
        color: '#8787A3',
        position: 'absolute',
        top: 1,
        left: 2,
    },
    collectionentryNumber: {
        justifyContent: 'center',
        backgroundColor: '#C7CFFF',
        width : 60,
        height: 16,
        marginBottom: 8,
    },
    collectionentryNumberText: {
        color: '#fff',
        fontSize: 12,
        textAlign: 'center',
    },

    //petCollectionInfo
    petGrowth: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center', 
        height: 60,
        width: '100%',
    },
    petimg:{
        width: 52,
        height: 52,
    },
});