import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({  
    outerContainer: {
        flex: 1,
        backgroundColor: "#D3D3DD",
        padding: 4,
    },
    container:{       
        flex: 1, 
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'column',
    },
    mainBody: {
        flex: 1,
        alignItems: 'center',
        width: '100%',
        height: 734,
        borderWidth: 3,
        borderColor: '#8787A3',
        backgroundColor: '#F3F8FE',
        paddingTop: 12,
        paddingLeft: 24,
        paddingRight: 24,
        paddingBottom: 12,
    },
    titleContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        backgroundColor: "#C7CFFF",
        borderTopWidth: 3,
        borderLeftWidth: 3,
        borderColor: "#FFF",
    },
    menuBarContainer: {
        backgroundColor:"#D3D3DD",
        flexDirection:"row",
        gap:8,
        paddingHorizontal:12,
        paddingVertical:4
    },
    tabBarContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        width:"100%",
        height: 12,
        backgroundColor: "#C7CFFF",
        borderColor: "#FFF",
        borderTopWidth: 3,
        borderLeftWidth: 3,
    },
    buttonText: {
        fontFamily: 'PF stardust ExtraBold',
        color: '#8787A3',
        fontSize: 14,
        textAlign: 'center',
    },
    toggleContainer: {
        width: '100%',
        height: 40,
        borderRadius: 20,
        padding: 5,
        flexDirection: 'row',
        alignItems: 'center',
        position: 'relative',
        overflow: 'hidden',
      },
      on: {
        backgroundColor: '#D3D3DD',
      },
      off: {
        backgroundColor: '#BFE1E0',
      },
      onLabel: {
        position: 'absolute',
        left: 10,
        zIndex: 1,
        color: 'white',
        fontWeight: 'bold',
      },
      offLabel: {
        position: 'absolute',
        right: 10,
        zIndex: 1,
        color: 'white',
        fontWeight: 'bold',
      },
      circle: {
        width: 30,
        height: 30,
        borderRadius: 15,
        backgroundColor: 'white',
        position: 'absolute',
        left: 5,
        top: 5,
      },

      
    optionButton: {
        width: 80,
        height: 32,
        padding: 8,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
    },
    agreeButton: {
        width: 172,
        height: 36,
        backgroundColor: '#BfE1E0',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },    
    disagreeButton: {
        width: 172,
        height: 36,
        backgroundColor: '#FFCDD9',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },    
    nextButton: {
        width: 172,
        height: 36,
        backgroundColor: '#ffdbb7',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },

    inputBox: {
        color: '#8787a3',
        fontSize: 14,
        textAlign: 'left',
        width: 284,
        height: 45,
        backgroundColor: '#fff',
        borderColor: '#8787a3',
        borderWidth: 1,
        marginBottom: 8,
        padding: 10,
        wordWrap: 'break-word', 
    },
    optionNickNameInputBox: {
        color: '#8787a3',
        fontSize: 20,
        textAlign: 'left',
        width: 240,
        height: 28,
        marginBottom: 8,
        padding: 4,
    },
    optionInputBox: {
        color: '#8787a3',
        fontSize: 14,
        textAlign: 'left',
        width: 200,
        height: 52,
        backgroundColor: '#fff',
        borderColor: '#8787a3',
        borderWidth: 1,
        marginBottom: 8,
        padding: 10,
    },
    title:{
        backgroundColor: '#c7cfff',
        width: 334,
        height: 59,
        borderColor: '#fff',
        borderLeftWidth: 3,
        borderTopWidth: 3,
    },


    //profile
    profile: {
        width: '100%',
        alignItems: 'center',
        flexDirection: 'row',
        marginBottom: 4,
    },
    profileImg: {
        width: 100,
        height: 100,
        borderRadius: 100 / 2,
        backgroundColor: '#fff',
        marginRight: 8,
    },
    profileId: {
        fontFamily: 'PF stardust ExtraBold',
        fontSize: 12,
        color: '#D3D3DD',
    },
    profileNickname: {
        color: '#9482CE',
        fontFamily: 'PF stardust ExtraBold',
        fontSize: 24,
        position: 'absolute',
        transform: [{ translateX: 1 }, { translateY: 1 }],
    },
    profileNicknameshadow: {
        color: '#CED5FF',
        fontFamily: 'PF stardust ExtraBold',
        fontSize: 24,
        transform: [{ translateX: 0 }, { translateY: 0 }],
    },
    profileMessegeBox: {
        width: '100%',
        height: 52,
        padding: 8,
    },
    profileMessege:{
        fontFamily: 'PF stardust ExtraBold',
        fontSize: 12,
        color: '#8787A3',
        marginLeft: -4,
    },
    profileTagList: {
        flexDirection: 'row',
    },
    profileTag: {
        fontFamily: 'PF stardust ExtraBold',
        fontSize: 12,
        color: '#fff',
        backgroundColor: '#BFE1E0',
        marginRight: 4,
        padding: 2,
    },



    //friend
    friendButtons: {
        backgroundColor: '#8787A3',
        flex: 1,
        justifyContent: 'center',
        borderColor: '#8787A3',
        borderTopWidth: 1,
        borderLeftWidth: 1,
        borderRightWidth: 1,
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        height: 30,
    },
    selectFriendButtons:{
        backgroundColor: 'none',
    },
    friendButtonsText: {
        fontFamily: 'PF stardust ExtraBold',
        fontSize: 14,
        color: '#fff',
        textAlign: 'center',
    },
    selectFriendButtonsText:{
        color: '#8787A3'
    },
    friendListButtons: {
        alignItems: 'center',
        flex: 1,
        flexDirection: 'row',
        marginBottom: 12,
    },
    friendContainer: {
        flexDirection: "row",
        marginTop: 12,
    },
    friendButtonsLine: {
        marginBottom: 12,
        height: 30,
        borderColor: '#8787A3',
        borderBottomWidth: 1,
        width: 4,
    },


    //friendList: 친구목록
    friendprofile: {
        flexDirection: 'row',
        marginRight: 8,
        marginBottom: 8,
    },
    friendprofileText: {
        backgroundColor: '#BFE1E0',
        flex: 1,
        borderColor: '#8787A3',
        borderWidth: 1,
        borderTopEndRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        padding: 8,
        position: 'relative',
        zIndex: 2,
    },
    friendprofileNickname: {
        color: '#9482CE',
        fontFamily: 'PF stardust ExtraBold',
        fontSize: 20,
        position: 'absolute',
        transform: [{ translateX: 1 }, { translateY: 1 }],
        marginBottom: 4,
    },
    friendprofileNicknameshadow: {
        color: '#CED5FF',
        fontFamily: 'PF stardust ExtraBold',
        fontSize: 20,
        transform: [{ translateX: 0 }, { translateY: 0 }],
        marginBottom: 4,
    },
    friendprofileTextShadow:{
        width: '100%',
        height: '100%',
        backgroundColor: '#8787A3',
        borderColor: '#8787A3',
        borderWidth: 1,
        borderTopEndRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        marginRight: 8,
        position: 'absolute',
        top: 2,
        left: 3,
        zIndex: 1,
    },
    friendProfileImgBoX:{
        alignSelf: 'flex-start',    
        borderRadius: 54 / 2,
        width: 54,
        height: 54,
        backgroundColor: '#fff',
        marginRight: 4,
    },
    friendProfileImg: {
        width: 54,
        height: 54,
        borderRadius: 100 / 2,
        marginRight: 8,
    },
    friendprofileText_another: {
        backgroundColor: '#CED5FF',
        flex: 1,
        borderColor: '#8787A3',
        borderWidth: 1,
        borderTopStartRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        padding: 8,
        position: 'relative',
        zIndex: 2,
    },
    friendprofileTextShadow_another: {
        width: '100%',
        height: '100%',
        backgroundColor: '#8787A3',
        borderColor: '#8787A3',
        borderWidth: 1,
        borderTopStartRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        marginRight: 8,
        position: 'absolute',
        top: 2,
        left: 3,
        zIndex: 1,
    },
    profileImgBox_another: {
        alignSelf: 'flex-start',  
        width: 54,
        height: 54,
        borderRadius: 54 / 2,
        backgroundColor: '#fff',
        flexDirection: 'column',
    },

    //친구list : 받은 요청
    friendRequest: {
        backgroundColor: '#fff',
        flex: 1,
        borderColor: '#8787A3',
        borderWidth: 1,
        borderTopEndRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        padding: 8,
    },
    profileRequestbutton: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 8,
    },
    profileRequestAccept: {
        width: '30%',
        minWidth: 104,
        height: 24,
        backgroundColor: '#BFE1E0',
        fontFamily: 'PF stardust ExtraBold',
        color: '#8787A3',
        marginLeft: 4,
        marginRight: 4,
        justifyContent: 'center',
    },
    profileRequestReject: {
        width: '30%',
        minWidth: 104,
        height: 24,
        backgroundColor: '#FFCDD9',
        fontFamily: 'PF stardust ExtraBold',
        color: '#8787A3',
        marginLeft: 4,
        marginRight: 4,
        justifyContent: 'center',
    },
    friendRequestWaiting: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'center',
        marginTop: 8,
        marginLeft: 4,
    },
    friendRequestWaitingText: {
        textAlign: 'left',
        fontFamily: 'PF stardust ExtraBold',
        fontSize: 12,
        color: '#8787A3',
    },

});